name: Sunrize
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29427
title: home page  web builder and lead generator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f2b634'
    - '#262425'
    - '#969596'
    - '#4b494a'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
