name: Sunrize
favicon: null
layout_spectrum: 0.9063225153367966
typography_spectrum: 0.21709435945376754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.07966420333832502
  lightness: 0.5210528397001326
  saturation: 0.02030338067561388
  rhythmicContrast: 0.9810165849048644
purpose: []
